version: '1'

services:
  api:
    build: .
    container_name: gemini_api
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - gemini-network
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gemini
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - gemini-network

networks:
  gemini-network:
    driver: bridge